server:
  port: 8082
spring:
  main:
    banner-mode: off
  application:
    name: &applicationName application-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:tariff_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: 'classpath:db-migrations/applications-changelog.xml'
    enabled: true

# Настройки для интеграции
services:
  tariff:
    url: http://localhost:8080/api/v1/calculation
  client:
    url: http://localhost:8081/api/v1/clients