services:
  # --- СЕРВИС БАЗЫ ДАННЫХ (PostgreSQL) ---
  postgres:
    image: postgres:17.6
    container_name: tariff-bot-db
    ports:
      - "5432:5432"  # Открываем порт наружу, чтобы IDEA могла подключиться
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data # Сохраняем данные в папку pg_data в корне проекта
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- СЕРВИС ПРИЛОЖЕНИЯ (Пока закомментирован для удобства разработки) ---
  # app:
  #   build: .
  #   container_name: tariff-bot-app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     # Передаем переменные внутрь Java-приложения
  #     - DB_NAME=${DB_NAME}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - BOT_TOKEN=${BOT_TOKEN}
  #     - BOT_USERNAME=${BOT_USERNAME}
  #     # ВАЖНО: Внутри Docker используем имя сервиса 'postgres' вместо 'localhost'
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
  #   ports:
  #     - "8080:8080"
  #   restart: on-failure